#!/usr/bin/env ansible-playbook
---
- import_playbook: tasks/system_files.yml
- import_playbook: tasks/packages.yml
- import_playbook: tasks/disable_services.yml
- import_playbook: tasks/git_configure.yml
- import_playbook: tasks/dell.yml
- import_playbook: tasks/munin.yml
# - import_playbook: tasks/libvirt.yml
- import_playbook: tasks/libvirt_tls.yml
- import_playbook: tasks/drbd.yml
- import_playbook: tasks/corosync.yml
- import_playbook: tasks/ocfs2.yml
#- import_playbook: tasks/drbd_resources.yml
#- import_playbook: tasks/drbd_status.yml
#- import_playbook: tasks/corosync_resources.yml
#- import_playbook: tasks/clvm_resources.yml
#- import_playbook: tasks/ocfs2_files.yml
#- import_playbook: tasks/ocfs2_format.yml
#- import_playbook: tasks/restart_services.yml
#- import_playbook: tasks/services.yml
