#!/usr/bin/env ansible-playbook
---
- name: Cluster Prereqs
  hosts: drbd-cluster
  any_errors_fatal: true
  tasks:
  - name: Upgrade Packages
    apt:
      upgrade: dist
      update_cache: yes
  - name: Install Prereq Packages
    apt: 'name={{item}} state=present update_cache=yes'
    with_items:
      - "apt-file"
      - "aptitude"
      - "bridge-utils"
      - "cluster-glue"
      - "clvm"
      - "cpu-checker"
      - "crmsh" 
      - "corosync"
      - "curl"
      - "dlm"
      - "dlm-controld"
      - "drbd-utils"
      - "fence-agents"
      - "git"
      - "gnutls-bin"
      - "heartbeat"
      - "haveged"
      - "ipmitool"
      - "libvirt-bin"
      - "lvm2"
      - "lvm2-lockd"
      - "minicom"
      - "mrtg"
      - "net-tools"
      - "ocfs2-tools"
      - "pcs"
      - "pacemaker"
      - "python3-pip"
      - "qemu"
      - "qemu-kvm"
      - "screen"
      - "snmpd"
      - "rsync"
      - "resource-agents"
      - "virtinst"
      - "wget"
