#!/usr/bin/env ansible-playbook
---
- name: Cluster Prereqs
  hosts: drbd-cluster
  any_errors_fatal: true
  tasks:
  - name: Upgrade Packages
    apt:
      upgrade: dist
      update_cache: yes
  - name: Install Prereq Packages
    apt: 'name={{item}} state=installed update_cache=yes'
    with_items:
      - "aptitude"
      - "cluster-glue"
      - "crmsh" 
      - "corosync"
      - "curl"
      - "drbd-utils"
      - "fence-agents"
      - "git"
      - "heartbeat"
      - "minicom"
      - "net-tools"
#     - "openais"
      - "ocfs2-tools"
      - "pacemaker"
      - "python3-pip"
      - "screen"
      - "rsync"
      - "resource-agents"
#      - "redhat-cluster-modules"
      - "wget"
