#!/usr/bin/env ansible-playbook
---
- name: Disable clusters core services from being started after reboot
  hosts: drbd-cluster

  tasks:
  - name: Disabling startup of corosync, pacmaker and pcsd
<<<<<<< HEAD
    script: ../files/disable_cluster_startup.sh
=======
    script: ../files/bin/disable_cluster_startup.sh
>>>>>>> 4c878416dd3db3a85089c35c938199429ebb133b
