#!/usr/bin/env ansible-playbook
---
- name: CLVM Configure locking type
  hosts: drbd-cluster

  tasks:

  - name: Create /etc/lvm/lvm.conf
    script: ../files/clvm/lvm.conf.sh

  - name: clvm service stop
    service:
      name: lvm2-clvmd
      enabled: false
      state: stopped
