#!/usr/bin/env ansible-playbook
---
- name: Corosync Key generation
  hosts: drbd-cluster

  tasks:
  - name: Create /etc/corosync/corosync.conf
#    template:
#      src: ../templates/corosync.conf.j2
#      dest: /etc/corosync/corosync.conf
    script: ../files/corosync.conf.sh
  - stat: 
      path: /etc/corosync/authkey
    register: corosync_authkey
    when: ansible_hostname == "virt-cl-drbd-0"

  - name: Corosync key generation on node 0
    command: 'corosync-keygen -l'
    when: 
      - ansible_hostname == "virt-cl-drbd-0"
      - corosync_authkey.stat.exists == false

  - name: Corosync copy /etc/corosync/authkey 
    synchronize:
      src: /etc/corosync/authkey
      dest: /etc/corosync/authkey
      rsync_opts:
        - "-e ssh"
    when: ansible_hostname == "virt-cl-drbd-1"
