#!/usr/bin/env ansible-playbook
---
- name: Corosync Key generation
  hosts: drbd-cluster

  tasks:
  - stat: 
      path: /etc/corosync/authkey
    register: corosync_authkey
    when: ansible_hostname == "virt-cl-drbd-0"

  - name: create directory if they don't exist
    file:
      path: "{{ item }}"
      state: directory
      owner: root
      group: root
      mode: 0775
    with_items:
      - /etc/corosync/service.d
      - /etc/corosync/examples.crm

  - name: Create /etc/corosync/corosync.conf
    template:
      src: ../templates/corosync/corosync.conf.j2
      dest: /etc/corosync/corosync.conf

  - name: Corosync key generation on node 0
    command: 'corosync-keygen -l'
    when: 
      - ansible_hostname == "virt-cl-drbd-0"
      - corosync_authkey.stat.exists == false

  - name: Corosync copy /etc/corosync/authkey 
    synchronize:
      src: /etc/corosync/authkey
      dest: /etc/corosync/authkey
      rsync_opts:
        - "-e ssh"
    when: ansible_hostname == "virt-cl-drbd-1"

  - name: Create /etc/corosync/service.d/pcmk
    template:
      src: ../templates/pacemaker/pcmk.j2
      dest: /etc/corosync/service.d/pcmk
