#!/usr/bin/env ansible-playbook
---
- name: Default Service state. 
  hosts: drbd-cluster

  tasks:
  - name: Stop and Disable Cluster Services from default startup
    service:
      name: "{{ item }}"
      enabled: no
      state: stopped
    with_items:
      - libvirtd
      - lvm2-clvmd
      - dlm
      - drbd
      - haveged
      - heartbeat
      - pacemaker
      - pcsd
      - corosync
      - ocfs2
      - o2cb
