#!/usr/bin/env ansible-playbook
---
- name: DRBD configuration for creation of one resource on a block device (sdb) specifically for clvm volumes
  hosts: drbd-cluster
  any_errors_fatal: true
  tasks:

  - name: Starting DRDB Syncronization on r0
    command: 'drbdadm primary --force r0'
#    when: ansible_hostname == 'virt-cl-drbd-0'
