#!/usr/bin/env ansible-playbook
---
- name: DRDB Configuration Files
  hosts: drbd-cluster
  any_errors_fatal: true
  tasks:

  - name: File for DRDB in /etc/drbd.d/global_common.conf
    script: ../files/drbd/global_common.conf.sh

  - name: File for DRDB in /etc/drbd.d/r0.res
    script: ../files/drbd/r0.res.sh

  - name: drbd service
    service:
      name: drbd
      enabled: false
      state: stopped


