#!/usr/bin/env ansible-playbook
---
- name: DRDB Configuration Files
  hosts: drbd-cluster
  any_errors_fatal: true
  tasks:
  - name: File for DRDB in /etc/drbd.d/global_common.conf
    script: ../files/drbd/global_common.conf.sh
