#!/usr/bin/env ansible-playbook
---
- name: Install Kubernetes Tooling on the Cluster Nodes.
  hosts: drbd-cluster
  gather_facts: no
  any_errors_fatal: true
  tasks:

  - name: Create a directory to hold Kubernetes/RKE deployment (/opt/k8s)
    file:
      path: /opt/k8s
      state: directory
      mode: 0755
      owner: root
      group: adm
      recurse: yes

  - name: Heketi (A GlusterFS Lifecycle Management API)
    git:
      repo: https://github.com/heketi/heketi
      dest: /opt/k8s/heketi
      clone: yes
      update: yes
      force: yes

  - name: OpenFAAS on Kubernetes
    git:
      repo: https://github.com/openfaas/faas-netes
      dest: /opt/k8s/faas-netes
      clone: yes
      update: yes
      force: yes

  - name: Install RancherLabs rke.
    get_url: 
      url: "https://github.com/rancher/rke/releases/download/v{{ rke_version }}/rke_linux-amd64"
      dest: "/usr/local/bin/rke"
      owner: "root"
      group: "root"
      mode: "0755"

  - name: Install kubectl.
    get_url: 
      url: "https://storage.googleapis.com/kubernetes-release/release/v{{ kubectl_version}}/bin/linux/amd64/kubectl"
      dest: "/usr/local/bin/kubectl"
      owner: "root"
      group: "root"
      mode: "0755"

  - name: Install kompose for converting docker-compose.yml to kubernetes.
    get_url: 
      url: "https://github.com/kubernetes/kompose/releases/download/v{{ kompose_version }}/kompose-linux-amd64"
      dest: "/usr/local/bin/kompose"
      owner: "root"
      group: "root"
      mode: "0755"

  - name: Download and decompress helm.
    unarchive:
      src: "https://storage.googleapis.com/kubernetes-helm/helm-v{{ helm_version }}-linux-amd64.tar.gz"
      dest: "/tmp/"
      remote_src: yes
    notify:
      - "Move helm and tiller"
      - "Change permisions on helm and tiller"

  handlers:

  - name: "Move helm and tiller"
    shell: "mv /tmp/linux-amd64/helm /usr/local/bin/helm && mv /tmp/linux-amd64/tiller /usr/local/bin/tiller"
    args:
      chdir: "/tmp"

  - name: Change permissions on helm and tiller
    file: 'name={{item}} mode=0755'
    with_items:
      - "/usr/local/bin/helm"
      - "/usr/local/bin/tiller"


