#!/usr/bin/env ansible-playbook
---
- name: Configuration of git username and email.
  hosts: 
  any_errors_fatal: true
  tasks:

  - name: apt Install git
    apt: 'name={{item}} state=present update_cache=yes'
    with_items:
      - "git"
    when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

  - name: yum Install git
    yum: 'name={{item}} state=present update_cache=yes'
    with_items:
      - "git"
    when: ansible_distribution == 'CentOS'

  - name: Adding git username
    command: 'git config --global user.name "Peter Pouliot"'

  - name: Adding git email
    command: 'git config --global user.email "peter@pouliot.net"'

