#!/usr/bin/env ansible-playbook
---
- name: Format OCFS2 resources
  hosts: drbd-cluster

  tasks:

  - stat:
      path: /dev/drbd0
    register: has_DRBD0

  - stat:
      path: lv_var_lib_libvirt_images
    register: has_lv_var_lib_libvirt_images

  - stat:
      path: lv_etc_libvirt_qemu
    register: has_lv_etc_libvirt_qemu

  - name: Format /dev/vg_cluster/lv_etc_libvirt_qemu with OCFS2 on node 0
    command: 'echo "y" | mkfs.ocfs2 --fs-feature-level=max-compat -F -N 2 -L "ocfs2" /dev/vg_cluster/lv_etc_libvirt_qemu'
    when: 
      - ansible_hostname == "virt-cl-drbd-0"
      - has_DRBD0 == true
      - has_lv_etc_libvirt_qemu == true
  - name: Format r0 with OCFS2 on node 0
    command: 'echo "y" | mkfs.ocfs2 --fs-feature-level=max-compat -F -N 2 -L "ocfs2" /dev/vg_cluster/lv_var_lib_libvirt_images'
    when: 
      - ansible_hostname == "virt-cl-drbd-0"
      - has_DRBD0 == true
      - has_lv_var_lib_libvirt_images == true
