#!/usr/bin/env ansible-playbook
---
- name: OCFS2 resources
  hosts: drbd-cluster

  tasks:
  - name: Format r0 with OCFS2 on node 0
    command: 'echo "y" | mkfs.ocfs2 -F -N 2 -L etc_libvirt_qemu /dev/drbd0'
    when: 
      - ansible_hostname == "virt-cl-drbd-0"
  - name: Format r0 with OCFS2 on node 0
    command: 'echo "y" | mkfs.ocfs2 -F -N 2 -L var_lib_libvirt_images /dev/drbd1'
    when: 
      - ansible_hostname == "virt-cl-drbd-0"
  - name: Create /etc/ocfs2/cluster.conf
    script: ../files/ocfs2_cluster.conf.sh
