#!/usr/bin/env ansible-playbook
---
- name: Format OCFS2 resources
  hosts: drbd-cluster

  tasks:
  - name: Format r0 with OCFS2 on node 0
    command: 'echo "y" | mkfs.ocfs2 --fs-feature-level=max-compat -F -N 2 -L "ocfs2" /dev/drbd0'
    when: 
      - ansible_hostname == "virt-cl-drbd-0"
  - name: Format r0 with OCFS2 on node 0
    command: 'echo "y" | mkfs.ocfs2 --fs-feature-level=max-compat -F -N 2 -L "ocfs2" /dev/drbd1'
    when: 
      - ansible_hostname == "virt-cl-drbd-0"
