#!/usr/bin/env ansible-playbook
---
- name: Required Cluster Packages
  hosts: drbd-cluster
  any_errors_fatal: true
  tasks:
  - name: Update Packages
    apt:
      upgrade: dist
      update_cache: yes

  - name: Upgrade all packages to the latest version
    apt:
        name: "*"
        state: latest

  - name: Installing Required Packages
    apt: 'name={{item}} state=present update_cache=yes'
    with_items:
      - "apt-file"
      - "aptitude"
      - "bridge-utils"
      - "cluster-glue"
      - "clvm"
      - "cpu-checker"
      - "crmsh" 
      - "corosync"
      - "curl"
      - "dlm"
      - "dlm-controld"
      - "drbd-utils"
      - "fence-agents"
      - "git"
      - "gnutls-bin"
      - "heartbeat"
      - "haveged"
      - "ipmitool"
      - "libvirt-bin"
      - "libguestfs-tools"
      - "libosinfo-bin"
      - "lvm2"
      - "lvm2-lockd"
      - "minicom"
      - "net-tools"
      - "ocfs2-tools"
      - "pcs"
      - "pacemaker"
      - "python-pip"
      - "python3-pip"
      - "qemu"
      - "qemu-kvm"
      - "resource-agents"
      - "rsync"
      - "screen"
      - "tree"
      - "virtinst"
      - "virt-goodies"
      - "virt-top"
      - "wget"
