#!/usr/bin/env ansible-playbook
---
- name: Restart cluster services
  hosts: drbd-cluster

  tasks:

  - name: pacemaker service restart
    service:
      name: pacemaker
      state: restarted

  - name: corosync service restart
    service:
      name: corosync
      state: restarted

  - name: pcsd service restart
    service:
      name: pcsd
      state: restarted
