#!/usr/bin/env ansible-playbook
---
- name: Enable Cluster Services
  hosts: drbd-cluster
  tasks:

  - name: pcsd service
    service:
      name: pcsd
      enabled: true
      state: running

  - name: pacemaker service
    service:
      name: pacemaker
      enabled: true
      state: running

  - name: corosync service
    service:
      name: corosync
      enabled: true
      state: running
