#!/usr/bin/env ansible-playbook
---
- name: DRDB /etc/hosts
  hosts: drbd-cluster
  any_errors_fatal: true
  tasks:
  - name: DRDB /etc/hosts
    file: src={{ item }} dest=/etc/hosts
    with_items:
     - ../files/hosts

  - name: DRDB /etc/netplan/01-netcfg.yml on node 0
    script: ../files/netplan/0/01-netcfg.yaml.sh
    when: ansible_hostname == "virt-cl-drbd-0"

  - name: DRDB /etc/netplan/01-netcfg.yml on node 1
    script: ../files/netplan/1/01-netcfg.yaml.sh
    when: ansible_hostname == "virt-cl-drbd-1"
