#!/usr/bin/env ansible-playbook
---
- name: Prep Cluster
  hosts: drbd-cluster
  any_errors_fatal: true
  tasks:
  - name: Upgrade Packages
    apt:
      upgrade: dist
      update_cache: yes
  - name: Install Prereq Packages
    apt: 'name={{item}} state=installed update_cache=yes'
    with_items:
      - "python3-pip"
      - "net-tools"
      - "rsync"
      - "wget"
      - "curl"
      - "screen"
      - "minicom"
      - "git"
      - "heartbeat"
      - "pacemaker"
      - "corosync"
      - "fence-agents"
#     - "openais"
      - "cluster-glue"
      - "resource-agents"
      - "drbd-utils"
      - "ocfs2-tools"

  - name: Sync /etc/ansible
    synchronize:
      mode: pull
      src: /etc/ansible
      dest: /etc/ansible

  - name: Create /etc/drbd.d/global_common.conf
    copy:
      dest: "/etc/drbd.d/global_common.conf"
      remote_src: no
      src: files/global_common.conf
