#!/usr/bin/env ansible-playbook
---
- name: DRBD configuration for creating two resources out of host lvm volumes.
  hosts: drbd-cluster
  any_errors_fatal: true
  tasks:

  - name: Creating DRDB resource r0
    command: 'echo "yes" | drbdadm create-md r0'

  - name: Enable DRDB resource r0
    command: 'drbdadm up r0'

  - name: Creating DRDB resource r1
    command: 'echo "yes" | drbdadm create-md r1'

  - name: Enable DRDB resource r1
    command: 'drbdadm up r1'

  - name: Starting DRDB Syncronization on r0
    command: 'drbdadm primary --force r0'
    when: ansible_hostname == 'virt-cl-drbd-0'

  - name: Starting DRDB Syncronization on r1
    command: 'drbdadm primary --force r1'
    when: ansible_hostname == 'virt-cl-drbd-0'

