#!/usr/bin/env ansible-playbook
---
- name: Shutdown All cluster resources gracefully
  hosts: drbd-cluster

  tasks:
  - name: Executing Shutdown Commands
    script: ../files/bin/shutdown_graceful.sh
