#!/usr/bin/env ansible-playbook
---
- name: Starting cluster infrastructure core services on both cluster nodes
  hosts: drbd-cluster

  tasks:

  - name: Stop and disable of "corosync", "pacmaker" and "pcsd" services on both cluster nodes.
    service: 'name={{ item }} enabled=false state=stopped'
    with_items:
      - pcsd
      - pacemaker
      - corosync
